### ISSUE TITLE
Fails to load SileoDepiction JSON File

### ISSUE THREAD

**Issue by CobreDev** [PINPAL/Sileo-Depiction-WebViews#2]
I am trying this out for fun, and while I know it's still a WIP, It's not working for my depictions. When I go here:

`https://pinpal.github.io/Sileo-Depiction-WebViews/?json=https://raw.githubusercontent.com/mac-user669/repo/master/sileodepictions/LimelightRed.json&name=LimelightRed&dev=mac-user669`

It says "Failed to load SileoDepiction JSON File". It's probably something simple that I'm missing, but I can't figure it out. My JSON is here:

'https://raw.githubusercontent.com/mac-user669/repo/master/sileodepictions/LimelightRed.json'

The repo browser works fine on my repo, but just not the depictions.

Thanks!

**Comment by PINPAL** [comment]
Getting this error when passing your JSON file:

SyntaxError: Unexpected token ] in JSON at position 3107
    at JSON.parse (<anonymous>)
    at getSileoDepiction (depiction.js:39)

**Comment by PINPAL** [comment]
Looks like on Line 116 you have a comma after your DepictionMarkdownView object even though it's the last object in the array.

**Comment by PINPAL** [comment]
Does your depiction load fine in Sileo? I'll definitely look into trying to validate the JSON file in some way.

**Comment by CobreDev** [comment]
Thanks, that was it! I fixed it, and it works great!
