### ISSUE TITLE
[Ideas] [Enhancements] Here are a couple of ideas I had:

### ISSUE THREAD

**Issue by CobreDev** [PINPAL/Sileo-Depiction-WebViews#3]
First off, this looks great! However I think you should use a darker color than #ffffff in global.css. I would recommend using a color like #F9F9F9, just to make it not quite as bright. Also, while a switch is fine, you should add `@media (prefers-color-scheme: dark)` to the css, so that it changes to dark mode based on what the user has set for the system. You can see this in action on my website: [mac-user669.github.io](https://mac-user669.github.io). That's all I had for now, I may add more later. Also no worries if you don't add this stuff, it's just some random thoughts I had. Thanks!

**Comment by PINPAL** [comment]
Oh yeah I completely forgot about that media query! I'll definitely add that. Cheers

**Comment by CobreDev** [comment]
Awesome!
